// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Vec2,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  get body() {
    return __t.array(Vec2);
  },
  direction: __t.string(),
  nextDirection: __t.option(__t.string()).name("next_direction"),
  alive: __t.bool(),
});
