// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GameTick = __t.object("GameTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTick = __Infer<typeof GameTick>;

export const Message = __t.object("Message", {
  sender: __t.identity(),
  sent: __t.timestamp(),
  text: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const Pellet = __t.object("Pellet", {
  id: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
});
export type Pellet = __Infer<typeof Pellet>;

export const Ping = __t.object("Ping", {
  identity: __t.identity(),
  clientSentMicros: __t.u64(),
});
export type Ping = __Infer<typeof Ping>;

export const Snake = __t.object("Snake", {
  identity: __t.identity(),
  get body() {
    return __t.array(Vec2);
  },
  direction: __t.string(),
  nextDirection: __t.option(__t.string()),
  alive: __t.bool(),
});
export type Snake = __Infer<typeof Snake>;

export const SpawnCounter = __t.object("SpawnCounter", {
  id: __t.u64(),
  value: __t.u64(),
});
export type SpawnCounter = __Infer<typeof SpawnCounter>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
});
export type User = __Infer<typeof User>;

export const Vec2 = __t.object("Vec2", {
  x: __t.i32(),
  y: __t.i32(),
});
export type Vec2 = __Infer<typeof Vec2>;

